module.exports={
    Admin:{
        Root:"/",
        Home:"/Admin/Home",
        ManageSubAdmins:"/Admin/ManageSubAdmins",
        ConfigForm:"/Admin/ConfigureForm",
        SubAdmin:"/Admin/SubAdmin",
        BulkExcelUpload:"/Admin/BulkExcelUpload"
    },
    Login:"/Login",
    server:{
        url:"http://localhost:8080",
        Login:"/Login",
        Verify:"/verify"
    }
}